name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.x ]
    env:
      SSH_KEY: ${{ secrets.HOST_KEY }}
      SSH_HOST: ${{ secrets.HOST }}
      SSH_USER: ${{ secrets.HOST_USERNAME }}
      SSH_PORT: ${{ secrets.HOST_PORT }}
      SSH_BUILD_DIR: ${{ secrets.PROD_HOST_BUILD_DIR }}
      PATH_TO_PM2: ${{ secrets.PATH_TO_PM2 }}
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install Dependencies
        run: npm i
      - name: "Setup Build Cache"
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.[jt]s', '**/*.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      - name: Building Project
        run: npm run build
      - name: Deploy
        run: |
          mkdir ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/github-actions
          chmod 400 ~/.ssh/github-actions
          echo -e "Host vps\n\tUser $SSH_USER\n\tHostname $SSH_HOST\n\tPort $SSH_PORT\n\tIdentityFile ~/.ssh/github-actions\n\tStrictHostKeyChecking No" >> ~/.ssh/config
          ssh vps "cd bombies/greens-restaurant-website-staging && git stash && git pull"
          ssh vps "export PATH=/home/carter/.nvm/versions/node/v20.5.1/bin npm i && npx prisma generate";
          rsync -re ssh ./.next/ vps:$SSH_BUILD_DIR
          ssh vps "export PATH='$PATH_TO_PM2'; pm2 restart GreensRestaurant"